apiVersion: v1
kind: Service
metadata:
  name: app-neo4j-external-service
  namespace: {{ .Values.namespace }}  # Specify your namespace
spec:
  selector:
    app: app
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: {{ .Values.neo4j.boltPort }}     # Optional, used for clarity
    targetPort: {{ .Values.neo4j.boltPort }}
    protocol: TCP
