apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  NEO4J_USER: {{ .Values.neo4j.username | b64enc | quote }}
  NEO4J_PASSWORD: {{ .Values.neo4j.password | b64enc | quote }}
