apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: {{ .Values.namespace }}
data:
  NEO4J_BOLT_PORT: "{{ .Values.neo4j.boltPort }}"
  NEO4J_HTTP_PORT: "{{ .Values.neo4j.httpPort }}"
