apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  namespace: {{ .Values.namespace }}  # Specify your namespace
spec:
  clusterIP: None  # Headless service with no ClusterIP
  selector:
    app: neo4j
  ports:
    - name: bolt
      port: {{ .Values.neo4j.boltPort | int }}  # Neo4j Bolt port
    - name: http
      port: {{ .Values.neo4j.httpPort | int }}  # Neo4j HTTP port
