apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv
  namespace: {{ .Values.namespace }}  # Specify your namespace
spec:
  capacity:
    storage: {{ .Values.neo4j.pv.storage }}  # Size of the volume
  accessModes:
    - {{ .Values.neo4j.pv.access }}  # This allows a single pod to mount the volume
  persistentVolumeReclaimPolicy: {{ .Values.neo4j.pv.recpolicy }}
  storageClassName: {{ .Values.neo4j.pv.storageclass }}  # Specify the storage class name (can be dynamic or static)
  claimRef:
    namespace: {{ .Values.namespace }}
    name: neo4j-pvc
  hostPath:
    path: {{ .Values.neo4j.pv.hostpath }}  # Use hostPath for local storage, adjust for your case
