apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
  namespace: {{ .Values.namespace }}  # Specify your namespace
spec:
  accessModes:
    - {{ .Values.neo4j.pv.access }}
  resources:
    requests:
      storage: {{ .Values.neo4j.pv.storage }}  # Size requested by the StatefulSet
  storageClassName: {{ .Values.neo4j.pv.storageclass }}  # Specify the storage class name
  
